# Update these paths inside your helm-chart/values.yaml file
gatewayService:
  image:
    repository: 775935273911.dkr.ecr.ap-south-1.amazonaws.com/submission-gateway-service
    tag: latest
    pullPolicy: Always

userService:
  image:
    repository: 775935273911.dkr.ecr.ap-south-1.amazonaws.com/submission-user-service
    tag: latest
    pullPolicy: Always

orderService:
  image:
    repository: 775935273911.dkr.ecr.ap-south-1.amazonaws.com/submission-order-service
    tag: latest
    pullPolicy: Always

productService:
  image:
    repository: 775935273911.dkr.ecr.ap-south-1.amazonaws.com/submission-product-service
    tag: latest
    pullPolicy: Always
