apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.containerPort }}
  selector:
    app: {{ .Release.Name }}-frontend
